import React, { useState } from "react";
import { HelpCircle, ChevronDown, Clock, ShieldCheck, DollarSign, ArrowRight, Sparkles, Check } from "lucide-react";
import { motion, AnimatePresence } from "motion/react";

interface FaqItem {
  id: string;
  question: string;
  answer: string;
  category: "timeline" | "payout" | "privacy";
  icon: React.ComponentType<any>;
}

export default function HelpFaq() {
  const [expandedId, setExpandedId] = useState<string | null>(null);
  const [activeCategory, setActiveCategory] = useState<"all" | "timeline" | "payout" | "privacy">("all");

  const faqs: FaqItem[] = [
    {
      id: "time-1",
      question: "How long does it take to process my chat dataset and clear JMD funds?",
      answer: "In compliance with international automated AML standards and LLM validation practices, standard evaluation payouts require a 7 to 14 business days clearance window. During this phase, auditing servers run strict synthetic duplication filters, spam-prevention audits, and verify that the dialogue models meet rigorous instructional-following quality constraints before triggering disbursements to your registered WiPay merchant wallet.",
      category: "timeline",
      icon: Clock,
    },
    {
      id: "time-2",
      question: "Can I expedite the auditing queue?",
      answer: "Currently, all batches enter a standardized algorithmic audit pipeline. Submitting high-quality, continuous conversations with natural questions and clear instructions (as opposed to disconnected single-word lines) prevents manual screening triggers and ensures speedier validation within the standard 7-14 day window.",
      category: "timeline",
      icon: Clock,
    },
    {
      id: "pay-1",
      question: "How exactly are my dialogue turns priced and calculated?",
      answer: "MindWave buys accepted anonymized chat pairs by value tier. Low-value but valid conversation earns JMD $5, contextual conversation earns JMD $12, Patois/code-switching language value earns JMD $18, creative or cultural insight earns JMD $28, and strong instructional/task-solving pairs earn JMD $35 base. Verified multiplier bonuses are capped so the displayed customer rate does not exceed JMD $50 per accepted pair.",
      category: "payout",
      icon: DollarSign,
    },
    {
      id: "pay-2",
      question: "What items or texts are filtered out as 'not useful' (zero value)?",
      answer: "We automatically filter and discard: system-generated alerts ('Media omitted', 'This message was deleted', bot responses, autogenerated broadcasts), greeting-only logs ('hello', 'hi'), laughing-only text sequences ('lol', 'lmao', 'giggle'), repetitive copies, and turns with no usable context. Patois is welcome. It is scored on meaning, context, and usefulness, not on sounding like standard English.",
      category: "payout",
      icon: DollarSign,
    },
    {
      id: "pay-3",
      question: "Are WhatsApp Voice Notes supported for payouts?",
      answer: "Not yet, but this dynamic audio capability is coming soon! Real-world speech recordings carrying natural Caribbean dialects and accents represent highly demanded training data for international speech synthesis and transcription models. We are designing a fully isolated browser speech transcriber. You can insert your contact details in our 'Voice Notes Notification' waitlist card in the Home View to get notified the second this unlocks.",
      category: "payout",
      icon: DollarSign,
    },
    {
      id: "priv-1",
      question: "How is my personal privacy secured when submitting WhatsApp chats?",
      answer: "Your browser extracts the WhatsApp export locally. The server receives temporary raw text only to sanitize, segment, and score it. Stored datasets, downloaded JSON, moderator views, and public ledger records should contain anonymized speaker tags, sanitized text, relative context metadata, and safe receipt information instead of raw source lines, names, emails, phone numbers, or absolute timestamps.",
      category: "privacy",
      icon: ShieldCheck,
    },
    {
      id: "priv-2",
      question: "How does the Driver's Licence redaction camera template protect my ID?",
      answer: "Compliance mandates require official photo ID logs to register a disbursement node. Our custom Camera / Upload module renders your image file onto a client-side canvas and writes solid 98% opacity blackout rectangles over highly sensitive portions (your Face area and your Taxpayer Registration Number / TRN). These modifications are permanently burned into the image pixels in the browser context; the raw, unredacted original ID image is immediately destroyed in memory.",
      category: "privacy",
      icon: ShieldCheck,
    },
  ];

  const toggleExpand = (id: string) => {
    setExpandedId(expandedId === id ? null : id);
  };

  const filteredFaqs = faqs.filter(
    (faq) => activeCategory === "all" || faq.category === activeCategory
  );

  return (
    <div className="mt-16 bg-[#060b17] border border-slate-800/80 rounded-3xl p-6 sm:p-10 space-y-8" id="help-faq-module">
      <div className="flex flex-col md:flex-row items-start md:items-end justify-between gap-4 border-b border-slate-800/60 pb-6">
        <div className="space-y-2">
          <div className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-emerald-950/40 border border-emerald-900/40 text-emerald-400 text-[10px] font-mono font-bold tracking-wider uppercase">
            <HelpCircle className="w-3.5 h-3.5" />
            Clear Guidance Info Hub
          </div>
          <h2 className="text-2xl font-display font-semibold text-white tracking-tight">Help &amp; Frequently Asked Questions</h2>
          <p className="text-slate-400 text-xs max-w-xl">
            Read transparent protocols regarding JMD settlements, temporary text processing, privacy-safe storage, and AI auditing metrics.
          </p>
        </div>

        {/* Category Tabs */}
        <div className="flex flex-wrap gap-1 bg-[#03060c] p-1 rounded-xl border border-slate-900 self-start md:self-auto">
          {(["all", "timeline", "payout", "privacy"] as const).map((cat) => (
            <button
              key={cat}
              onClick={() => {
                setActiveCategory(cat);
                setExpandedId(null);
              }}
              className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all uppercase tracking-wide font-mono ${
                activeCategory === cat
                  ? "bg-emerald-500 text-slate-950"
                  : "text-slate-400 hover:text-slate-200 hover:bg-slate-900/40"
              }`}
            >
              {cat}
            </button>
          ))}
        </div>
      </div>

      {/* Grid of Highlight Bullet Points */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4" id="faq-quick-stats">
        <div className="p-4 bg-[#080d1a] border border-slate-800/40 rounded-2xl flex items-start gap-3">
          <div className="p-2 bg-emerald-950/45 border border-emerald-800/30 rounded-xl text-emerald-400 shrink-0">
            <Clock className="w-4 h-4" />
          </div>
          <div className="space-y-1">
            <h4 className="text-xs font-bold font-mono text-slate-300 uppercase tracking-wide">Payout Timeline</h4>
            <p className="text-[11px] text-slate-400 leading-relaxed">
              7-14 business days direct clearance window to WiPay merchant accounts.
            </p>
          </div>
        </div>

        <div className="p-4 bg-[#080d1a] border border-slate-800/40 rounded-2xl flex items-start gap-3">
          <div className="p-2 bg-teal-950/45 border border-teal-800/30 rounded-xl text-teal-400 shrink-0">
            <DollarSign className="w-4 h-4" />
          </div>
          <div className="space-y-1">
            <h4 className="text-xs font-bold font-mono text-slate-300 uppercase tracking-wide">Calculations</h4>
            <p className="text-[11px] text-slate-400 leading-relaxed">
              $5 - $50 JMD per accepted chat pair, based on usefulness, context, and language value.
            </p>
          </div>
        </div>

        <div className="p-4 bg-[#080d1a] border border-slate-800/40 rounded-2xl flex items-start gap-3">
          <div className="p-2 bg-slate-900/60 border border-slate-800 rounded-xl text-sky-400 shrink-0">
            <ShieldCheck className="w-4 h-4" />
          </div>
          <div className="space-y-1">
            <h4 className="text-xs font-bold font-mono text-slate-300 uppercase tracking-wide">Privacy Standard</h4>
            <p className="text-[11px] text-slate-400 leading-relaxed">
              Temporary raw-text processing with sanitized storage, plus browser-side ID image blackout.
            </p>
          </div>
        </div>
      </div>

      {/* Interactive Accordion List */}
      <div className="space-y-3" id="faq-interactive-accordion">
        {filteredFaqs.map((faq) => {
          const Icon = faq.icon;
          const isExpanded = expandedId === faq.id;

          return (
            <div
              key={faq.id}
              className={`border rounded-2xl transition-all duration-300 overflow-hidden ${
                isExpanded
                  ? "bg-[#090f1d] border-emerald-500/35"
                  : "bg-[#03070f] border-slate-800 hover:border-slate-700 hover:bg-[#050a16]"
              }`}
            >
              <button
                type="button"
                onClick={() => toggleExpand(faq.id)}
                className="w-full text-left p-5 flex items-start justify-between gap-4 font-semibold text-sm text-slate-200 transition-colors cursor-pointer"
              >
                <div className="flex items-start gap-3">
                  <div className={`p-1.5 rounded-lg shrink-0 mt-0.5 ${
                    isExpanded ? "bg-emerald-500/10 text-emerald-400" : "bg-slate-900/40 text-slate-500"
                  }`}>
                    <Icon className="w-4 h-4" />
                  </div>
                  <span className="text-sm font-semibold tracking-tight leading-relaxed text-slate-100 hover:text-white transition-colors">
                    {faq.question}
                  </span>
                </div>
                <div className={`p-1 rounded-lg bg-slate-950 border border-slate-800 text-slate-400 transition-transform duration-300 ${
                  isExpanded ? "rotate-180 border-emerald-500/30 text-emerald-400" : ""
                }`}>
                  <ChevronDown className="w-4 h-4" />
                </div>
              </button>

              <AnimatePresence initial={false}>
                {isExpanded && (
                  <motion.div
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: "auto", opacity: 1 }}
                    exit={{ height: 0, opacity: 0 }}
                    transition={{ duration: 0.2 }}
                  >
                    <div className="px-5 pb-5 pt-1 text-xs text-slate-400 border-t border-slate-900/60 leading-relaxed font-normal space-y-2">
                      <p>{faq.answer}</p>
                      <div className="flex items-center gap-1.5 pt-2 text-[10px] text-emerald-400 font-mono font-semibold">
                        <Check className="w-3 h-3" />
                        <span>VERIFIED COMPLIANCE STANDARD</span>
                      </div>
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>
          );
        })}
      </div>
    </div>
  );
}
